sudo: required
services:
    - docker
before_install:
    - docker build -t shibudas/complex -f ./client/Dockerfile.dev ./client
script:
    - docker run shibudas/complex npm test -- --coverage
after_success:
    - docker build -t shibudas/complex-client ./client
    - docker build -t shibudas/complex-nginx ./nginx
    - docker build -t shibudas/complex-server ./server
    - docker build -t shibudas/complex-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push complex-client
    - docker push complex-nginx
    - docker push complex-server
    - docker push complex-worker
